[package]
name = "sudoku-brutalizer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "0.7.0"
log = "0.4.14"
sudoku = "0.7.0"
wasm-logger = "0.2.0"
yew = "0.18.0"
